- web/modules/custom/farm_nfa/farm_nfa.module
> #82: Hide action buttons in dashboard page.

- web/modules/custom/farm_nfa/farm_nfa.routing.yml
> #84: Hide harvest tab on Natural Forest Plans.

- web/modules/custom/farm_nfa/farm_nfa.install
- web/modules/custom/farm_nfa/farm_nfa.module
> #83: Hide menu items

- composer.json
- patches/3236712-allow-render-custom-blocks.patch
- web/modules/custom/farm_nfa/farm_nfa.libraries.yml
- web/modules/custom/farm_nfa/farm_nfa.module
- web/modules/custom/farm_nfa/farm_nfa.routing.yml
- web/modules/custom/farm_nfa/js/farm_nfa_search_autocomplete.js
- web/modules/custom/farm_nfa/src/Controller/JsonApiAutocompleteController.php
- web/modules/custom/farm_nfa/src/Form/FarmNfaSearchBlockForm.php
- web/modules/custom/farm_nfa/src/Plugin/Block/FarmNfaSearchBlock.php
> #81: Dashboard asset search block

- composer.json
- patches/3236712-allow-render-custom-blocks.patch
- web/modules/custom/farm_nfa/farm_nfa.libraries.yml
- web/modules/custom/farm_nfa/farm_nfa.module
- web/modules/custom/farm_nfa/farm_nfa.routing.yml
- web/modules/custom/farm_nfa/js/farm_nfa_search_autocomplete.js
- web/modules/custom/farm_nfa/src/Controller/JsonApiAutocompleteController.php
- web/modules/custom/farm_nfa/src/Form/FarmNfaSearchBlockForm.php
- web/modules/custom/farm_nfa/src/Plugin/Block/FarmNfaSearchBlock.php
> #87: Dashboard plan search block

- web/modules/custom/farm_nfa/farm_nfa.module
- web/modules/custom/farm_nfa/modules/farm_nfa_cfr/farm_nfa_cfr.services.yml
- web/modules/custom/farm_nfa/modules/farm_nfa_cfr/src/Controller/GetTitleController.php
- web/modules/custom/farm_nfa/modules/farm_nfa_cfr/src/Routing/RouteSubscriber.php
- web/themes/custom/farm_gin/farm_gin.theme
Fixes https://github.com/mstenta/farm_nfa/issues/142
> Issue #142 Change 'Location' to 'Sectors & CFRs'

- web/modules/custom/farm_nfa/config/install/views.view.farm_asset.yml
- web/modules/custom/farm_nfa/farm_nfa.info.yml
Fixes https://github.com/Cambrico/farm_nfa/issues/166
> #166 Remove "is location", "is fixed" filters and "location" column on the assets dashboard

- web/modules/custom/farm_nfa/js/farmOS.map.behaviors.farm_nfa_gfw_layers.js
- web/modules/custom/farm_nfa/src/Form/ForestPlanGfwForm.php
fixed gfw api map issue:
1. too many requests on map rendering
2. alerts not getting rendered on prod
>  Gfw api map fixes

- web/modules/custom/farm_nfa/js/farmOS.map.behaviors.farm_nfa_gfw_layers.js
- web/modules/custom/farm_nfa/src/Form/ForestPlanGfwForm.php
fixed gfw api issues
demo video:
https://user-images.githubusercontent.com/58719389/219117619-5959ea5c-8c69-4af8-ad48-44847d02d8fa.mp4
api demo:
https://user-images.githubusercontent.com/58719389/219115930-6a0039d6-cef0-44c6-b826-7b0118bae06f.mp4
> #172: fixed gfw api issues

- web/modules/custom/farm_nfa/js/farmOS.map.behaviors.farm_nfa_gfw_layers.js
fixed deforestation alerts api issues
for demo purposes refer to this PR #228
> #172: fixed deforestation alerts api issues

- config/sync/asset.type.range.yml
- config/sync/asset.type.sector.yml
- config/sync/core.entity_form_display.asset.range.default.yml
- config/sync/core.entity_form_display.asset.sector.default.yml
- config/sync/core.entity_view_display.asset.range.default.yml
- config/sync/core.entity_view_display.asset.sector.default.yml
- config/sync/core.extension.yml
- config/sync/field.field.asset.range.range_cfr.yml
- config/sync/field.field.asset.sector.sector_cfr.yml
- config/sync/field.storage.asset.range_cfr.yml
- config/sync/field.storage.asset.sector_cfr.yml
- web/modules/custom/farm_nfa/farm_nfa.install
- web/modules/custom/farm_nfa/modules/farm_nfa_range/config/install/asset.type.range.yml
- web/modules/custom/farm_nfa/modules/farm_nfa_range/config/install/core.entity_form_display.asset.range.default.yml
- web/modules/custom/farm_nfa/modules/farm_nfa_range/config/install/core.entity_view_display.asset.range.default.yml
- web/modules/custom/farm_nfa/modules/farm_nfa_range/config/install/field.field.asset.range.range_cfr.yml
- web/modules/custom/farm_nfa/modules/farm_nfa_range/config/install/field.storage.asset.range_cfr.yml
- web/modules/custom/farm_nfa/modules/farm_nfa_range/farm_nfa_range.info.yml
- web/modules/custom/farm_nfa/modules/farm_nfa_range/src/Plugin/Asset/AssetType/Range.php
- web/modules/custom/farm_nfa/modules/farm_nfa_sector/config/install/asset.type.sector.yml
- web/modules/custom/farm_nfa/modules/farm_nfa_sector/config/install/core.entity_form_display.asset.sector.default.yml
- web/modules/custom/farm_nfa/modules/farm_nfa_sector/config/install/core.entity_view_display.asset.sector.default.yml
- web/modules/custom/farm_nfa/modules/farm_nfa_sector/config/install/field.field.asset.sector.sector_cfr.yml
- web/modules/custom/farm_nfa/modules/farm_nfa_sector/config/install/field.storage.asset.sector_cfr.yml
- web/modules/custom/farm_nfa/modules/farm_nfa_sector/farm_nfa_sector.info.yml
- web/modules/custom/farm_nfa/modules/farm_nfa_sector/src/Plugin/Asset/AssetType/Sector.php
added sector and range asset types
> Add new asset types

- web/modules/custom/farm_nfa/modules/farm_nfa_forest/farm_nfa_forest.module
fixed field updates issues on pre existing stand asset types
issue description : 
https://github.com/National-Forestry-Authority/forests/issues/54#issuecomment-1597199434
demo:
https://github.com/National-Forestry-Authority/forests/assets/58719389/644d8892-d7d6-431c-bf0a-80bfcd3dc858
> fixed form updation for existing forms

- web/modules/custom/farm_nfa/modules/farm_nfa_forest/farm_nfa_forest.module
fixed the listed issues for the forest edit and add forms
https://github.com/National-Forestry-Authority/forests/issues/54#issuecomment-1628864079
> Field choices fixes

- config/sync/views.view.asset_geojson.yml
- web/modules/custom/farm_nfa/config/install/views.view.asset_geojson.yml
- web/modules/custom/farm_nfa/deployments/9028/views.view.asset_geojson.yml
- web/modules/custom/farm_nfa/farm_nfa.info.yml
- web/modules/custom/farm_nfa/farm_nfa.install
- web/modules/custom/farm_nfa/farm_nfa.links.task.yml
- web/modules/custom/farm_nfa/farm_nfa.routing.yml
- web/modules/custom/farm_nfa/js/farmOS.map.behaviors.farm_nfa_gfw_layers.js
- web/modules/custom/farm_nfa/js/farmOS.map.behaviors.farm_nfa_plan_locations_layers.js
- web/modules/custom/farm_nfa/src/Form/ForestPlanGfwForm.php
added GFW tab to all location assets
demo:
https://github.com/National-Forestry-Authority/forests/assets/58719389/fb008da1-7ee4-437c-b164-f898de071081
> #273: added gfw tab to all assets

- web/modules/custom/farm_nfa/css/gfw_map.css
- web/modules/custom/farm_nfa/js/farmOS.map.behaviors.farm_nfa_gfw_layers.js
- web/modules/custom/farm_nfa/src/Form/ForestPlanGfwForm.php
added conditional date range picker rendering and custom date ranges
demo:
https://github.com/National-Forestry-Authority/forests/assets/58719389/beb7ba13-4c6f-473f-a7be-db199c606fb7
> Conditional date range picker rendering

- web/modules/custom/farm_nfa/css/gfw_map.css
- web/modules/custom/farm_nfa/js/farmOS.map.behaviors.farm_nfa_gfw_layers.js
- web/modules/custom/farm_nfa/src/Form/ForestPlanGfwForm.php
restricted data range picker to only show `Month to date` and `Last week` on ranges and sectors asset types
demo:
https://github.com/National-Forestry-Authority/forests/assets/58719389/b6111307-4be7-4384-9334-bc211e7c247a
> restricted date range picker

- web/modules/custom/farm_nfa/css/gfw_map.css
- web/modules/custom/farm_nfa/js/farmOS.map.behaviors.farm_nfa_gfw_layers.js
- web/modules/custom/farm_nfa/src/Form/ForestPlanGfwForm.php
improved loadiing for gfw map
demo:
https://github.com/National-Forestry-Authority/forests/assets/58719389/b85a42bd-422d-42f6-b7fd-d8ea7bb052df
> Improve gfw load

- config/sync/views.view.asset_children.yml
- web/modules/custom/farm_nfa/config/install/farm_map.map_behavior.farm_nfa_ranges_cfr_layer.yml
- web/modules/custom/farm_nfa/deployments/9033/farm_map.map_behavior.farm_nfa_ranges_cfr_layer.yml
- web/modules/custom/farm_nfa/deployments/9033/views.view.asset_children.yml
- web/modules/custom/farm_nfa/farm_nfa.info.yml
- web/modules/custom/farm_nfa/farm_nfa.install
- web/modules/custom/farm_nfa/farm_nfa.libraries.yml
- web/modules/custom/farm_nfa/js/farmOS.map.behaviors.farm_nfa_layerswitcher_sidebar.js
- web/modules/custom/farm_nfa/js/farmOS.map.behaviors.farm_nfa_ranges_cfr_layer.js
- web/modules/custom/farm_nfa/src/Form/ForestPlanGfwForm.php
- web/modules/custom/farm_nfa/src/MapRenderEventSubscriberDecorator.php
added cfr layer in ranges assets for gfw and main tab
demo: 
https://github.com/National-Forestry-Authority/forests/assets/58719389/85970af9-14cd-49f7-9fcb-e9efd571c141
> added cfr layer for ranges asset

- config/sync/views.view.asset_children.yml
- web/modules/custom/farm_nfa/config/install/views.view.asset_children.yml
- web/modules/custom/farm_nfa/deployments/9033/views.view.asset_children.yml
- web/modules/custom/farm_nfa/js/farmOS.map.behaviors.farm_nfa_ranges_cfr_layer.js
fixed loading issue for CFR layer of ranges asset
> range asset CFR layer loading fixes

- composer.json
- composer.lock
- web/modules/custom/farm_nfa/css/gfw_map.css
- web/modules/custom/farm_nfa/farm_nfa.libraries.yml
- web/modules/custom/farm_nfa/js/farmOS.map.behaviors.farm_nfa_gfw_layers.js
added the following gfw enhancements:
- on GFW map now each marker clickable. The popup displays lat/long, alert type, timestamp, and any other useful data sent back from the API.
-  a sortable table is shown below the map showing the same information, one row for each marker
- table is updated when the date range changes
- also have added pagination through list.js
demo:
https://github.com/National-Forestry-Authority/forests/assets/58719389/e6dd0789-4a93-44a5-92f0-10e2c764d406
> #354: added map enhancement

- web/modules/custom/farm_nfa/js/farmOS.map.behaviors.farm_nfa_gfw_layers.js
- web/modules/custom/farm_nfa/js/farmOS.map.behaviors.farm_nfa_plan_locations_layers.js
fixes popup UI on GFW CFR map
demo:
> Fix gfw map popup for CFRs

- .ddev/drupal-files/settings.local.php
- composer.json
- composer.lock
- config/sync/config/sync/key.key.gfw_api_key.yml
- config/sync/core.extension.yml
- docker-compose.portainer.yml
- docker/drupal/settings.overrides.php
- web/modules/custom/farm_nfa/config/install/key.key.gfw_api_key.yml
- web/modules/custom/farm_nfa/deployments/10013/key.key.gfw_api_key.yml
- web/modules/custom/farm_nfa/farm_nfa.info.yml
- web/modules/custom/farm_nfa/farm_nfa.install
- web/modules/custom/farm_nfa/farm_nfa.post_update.php
- web/modules/custom/farm_nfa/farm_nfa.services.yml
- web/modules/custom/farm_nfa/js/farmOS.map.behaviors.farm_nfa_gfw_layers.js
- web/modules/custom/farm_nfa/src/Form/ForestPlanGfwForm.php
- web/modules/custom/farm_nfa/src/MapRenderEventSubscriberDecorator.php
fixed alerts not working on GFW maps
demo:
https://github.com/user-attachments/assets/7f594998-46f9-4997-8502-7a1fc4f88596
> #386: fixed gfw alerts issue
